// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/centofai/Centofai.tsx": () => import("../components/mockups/centofai/Centofai.tsx"),
  "./components/mockups/hero-neu/HeroNeu.tsx": () => import("../components/mockups/hero-neu/HeroNeu.tsx")
};
